import type { EnrichedCoin } from './types'

// Famous placeholder coins for each theme to prevent empty results
// These are fully enriched coins with all required properties
export const FAMOUS_COINS_BY_THEME: Record<string, EnrichedCoin[]> = {
  cat: [
    {
      id: 'MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5',
      mint: 'MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5',
      name: 'cat in a dogs world',
      symbol: 'MEW',
      price: '$0.0055',
      priceUsd: 0.0055,
      change24h: '+12.5%',
      change24hNum: 12.5,
      marketCap: '$550M',
      marketCapUsd: 550000000,
      description: 'The first cat coin on Solana',
      image: 'https://logo.moralis.io/placeholder_cat_mew.webp',
      creator: 'MEW1gQ...cPP5',
      createdAt: new Date('2024-01-15'),
      age: '10m',
      liquidity: '$15M',
      volume24h: '$45M',
      txns24h: 25000,
      holders: 85000,
      isVerified: true,
      riskLevel: 'low' as const,
      launchpad: 'pumpfun',
      themes: ['cat'],
    },
    {
      id: '7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr',
      mint: '7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr',
      name: 'POPCAT',
      symbol: 'POPCAT',
      price: '$0.82',
      priceUsd: 0.82,
      change24h: '+8.3%',
      change24hNum: 8.3,
      marketCap: '$820M',
      marketCapUsd: 820000000,
      description: 'The viral cat meme coin',
      image: 'https://logo.moralis.io/placeholder_cat_popcat.webp',
      creator: '7GCihg...W2hr',
      createdAt: new Date('2024-02-20'),
      age: '8m',
      liquidity: '$25M',
      volume24h: '$65M',
      txns24h: 35000,
      holders: 125000,
      isVerified: true,
      riskLevel: 'low' as const,
      launchpad: 'raydium',
      themes: ['cat'],
    },
  ],
  dog: [
    {
      id: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
      mint: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
      name: 'Bonk',
      symbol: 'BONK',
      price: '$0.000025',
      priceUsd: 0.000025,
      change24h: '+5.2%',
      change24hNum: 5.2,
      marketCap: '$1.8B',
      marketCapUsd: 1800000000,
      description: 'The first Solana dog meme coin',
      image: 'https://logo.moralis.io/placeholder_dog_bonk.webp',
      creator: 'DezXAZ...B263',
      createdAt: new Date('2022-12-25'),
      age: '22m',
      liquidity: '$45M',
      volume24h: '$125M',
      txns24h: 85000,
      holders: 750000,
      isVerified: true,
      riskLevel: 'low' as const,
      launchpad: 'bonk',
      themes: ['dog'],
    },
    {
      id: 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',
      mint: 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',
      name: 'dogwifhat',
      symbol: 'WIF',
      price: '$2.15',
      priceUsd: 2.15,
      change24h: '+15.7%',
      change24hNum: 15.7,
      marketCap: '$2.1B',
      marketCapUsd: 2100000000,
      description: 'Dog with hat meme',
      image: 'https://logo.moralis.io/placeholder_dog_wif.webp',
      creator: 'EKpQGS...zcjm',
      createdAt: new Date('2023-11-20'),
      age: '11m',
      liquidity: '$55M',
      volume24h: '$180M',
      txns24h: 95000,
      holders: 250000,
      isVerified: true,
      riskLevel: 'low' as const,
      launchpad: 'raydium',
      themes: ['dog'],
    },
  ],
  pepe: [],
  trump: [],
  ai: [],
  nft: [],
  gaming: [],
}

export type ThemeId = keyof typeof FAMOUS_COINS_BY_THEME
